---
- name: install essential system libraries
  apt: name={{ item }} state=present
  with_items:
    - nginx
- name: setup nginx site
  template: src=templates/nginx/stratya.com.j2 dest=/etc/nginx/sites-available/stratya.com.conf
  notify:
  - restart nginx
