---
mysql_root_password_update: yes
mysql_root_password: unsaferootpassword
mysql_enabled_on_startup: yes
mysql_slow_query_log_enabled: yes
mysql_slow_query_log_file: /var/log/mysql-slow.log
mysql_slow_query_time: 2
mysql_databases:
  - name: stratya
    encoding: 'utf8'
    collation: 'utf8_general_ci'
mysql_users:
  - name: webservice
    host: "localhost"
    password: "changeit"
    priv: "stratya.*:ALL"
